import type { CalculatorMeta } from '../../core/types/capabilities';

// Registry de todas as calculadoras do módulo de Matemática
export const matematicaCalculators: CalculatorMeta[] = [
  {
    id: 'calc-basico',
    name: 'Calculadora Básica',
    description: 'Operações aritméticas fundamentais.',
    pluginArea: 'matematica',
    disciplineIds: ['calculo-i', 'matematica-basica'],
    capabilities: ['STEP_BY_STEP', 'HISTORY'],
    version: '1.0.0',
  },
  {
    id: 'calc-cientifico',
    name: 'Calculadora Científica',
    description: 'Funções trigonométricas, exponenciais e logarítmicas.',
    pluginArea: 'matematica',
    disciplineIds: ['calculo-i', 'calculo-ii'],
    capabilities: ['STEP_BY_STEP', 'HISTORY'],
    version: '1.0.0',
  },
  {
    id: 'calc-algebra',
    name: 'Álgebra e Equações',
    description: 'Equações de 1º e 2º grau, sistemas lineares.',
    pluginArea: 'matematica',
    disciplineIds: ['algebra-linear', 'matematica-basica'],
    capabilities: ['STEP_BY_STEP'],
    knowledgeFormulaIds: ['bhaskara'],
    version: '1.0.0',
  },
  {
    id: 'calc-symbolic',
    name: 'Cálculo Diferencial e Integral',
    description: 'Derivação, integração e simplificação simbólica.',
    pluginArea: 'matematica',
    disciplineIds: ['calculo-i', 'calculo-ii', 'calculo-iii'],
    capabilities: ['STEP_BY_STEP'],
    knowledgeFormulaIds: ['tensao-normal'],
    version: '1.0.0',
  },
  {
    id: 'calc-matrizes',
    name: 'Matrizes e Vetores',
    description: 'Operações matriciais, determinantes e inversas.',
    pluginArea: 'matematica',
    disciplineIds: ['algebra-linear', 'geometria-analitica'],
    capabilities: ['STEP_BY_STEP', 'GRAPH'],
    version: '1.0.0',
  },
  {
    id: 'calc-estatistica',
    name: 'Estatística',
    description: 'Medidas de tendência central, dispersão e probabilidade.',
    pluginArea: 'matematica',
    disciplineIds: ['estatistica', 'probabilidade'],
    capabilities: ['STEP_BY_STEP', 'GRAPH'],
    version: '1.0.0',
  },
  {
    id: 'calc-complexos',
    name: 'Números Complexos',
    description: 'Operações com números complexos em forma algébrica e polar.',
    pluginArea: 'matematica',
    disciplineIds: ['calculo-ii', 'algebra-linear'],
    capabilities: ['STEP_BY_STEP', 'GRAPH'],
    version: '1.0.0',
  },
];
